# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\ui\main.ui',
# licensing of 'src\ui\main.ui' applies.
#
# Created: Tue Apr 09 15:50:03 2019
#      by: pyside2-uic  running on PySide2 5.11.0a1.dev1528379875
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(564, 474)
        self.gridLayout_2 = QtWidgets.QGridLayout(MainWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.controller = MainController(MainWidget)
        self.controller.setObjectName("controller")
        self.gridLayout = QtWidgets.QGridLayout(self.controller)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.footer_layout = QtWidgets.QGridLayout()
        self.footer_layout.setObjectName("footer_layout")
        spacerItem = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.footer_layout.addItem(spacerItem, 0, 0, 1, 1)
        self.user_label = QtWidgets.QLabel(self.controller)
        self.user_label.setObjectName("user_label")
        self.footer_layout.addWidget(self.user_label, 0, 1, 1, 1)
        self.user_comboBox = CompleterCombobox(self.controller)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_comboBox.sizePolicy().hasHeightForWidth())
        self.user_comboBox.setSizePolicy(sizePolicy)
        self.user_comboBox.setObjectName("user_comboBox")
        self.footer_layout.addWidget(self.user_comboBox, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.footer_layout, 4, 0, 1, 1)
        self.header_layout = QtWidgets.QGridLayout()
        self.header_layout.setObjectName("header_layout")
        self.lable_group = QtWidgets.QVBoxLayout()
        self.lable_group.setObjectName("lable_group")
        self.show_lable = QtWidgets.QLabel(self.controller)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_lable.sizePolicy().hasHeightForWidth())
        self.show_lable.setSizePolicy(sizePolicy)
        self.show_lable.setObjectName("show_lable")
        self.lable_group.addWidget(self.show_lable)
        self.entity_lable = QtWidgets.QLabel(self.controller)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entity_lable.sizePolicy().hasHeightForWidth())
        self.entity_lable.setSizePolicy(sizePolicy)
        self.entity_lable.setObjectName("entity_lable")
        self.lable_group.addWidget(self.entity_lable)
        self.task_lable = QtWidgets.QLabel(self.controller)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_lable.sizePolicy().hasHeightForWidth())
        self.task_lable.setSizePolicy(sizePolicy)
        self.task_lable.setObjectName("task_lable")
        self.lable_group.addWidget(self.task_lable)
        self.header_layout.addLayout(self.lable_group, 0, 0, 2, 1)
        self.comboBox_group = QtWidgets.QGridLayout()
        self.comboBox_group.setObjectName("comboBox_group")
        self.show_comboBox = QtWidgets.QComboBox(self.controller)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_comboBox.sizePolicy().hasHeightForWidth())
        self.show_comboBox.setSizePolicy(sizePolicy)
        self.show_comboBox.setObjectName("show_comboBox")
        self.comboBox_group.addWidget(self.show_comboBox, 0, 0, 1, 1)
        self.entity_comboBox = QtWidgets.QComboBox(self.controller)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entity_comboBox.sizePolicy().hasHeightForWidth())
        self.entity_comboBox.setSizePolicy(sizePolicy)
        self.entity_comboBox.setObjectName("entity_comboBox")
        self.comboBox_group.addWidget(self.entity_comboBox, 0, 1, 1, 1)
        self.sequence_comboBox = CompleterCombobox(self.controller)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_comboBox.sizePolicy().hasHeightForWidth())
        self.sequence_comboBox.setSizePolicy(sizePolicy)
        self.sequence_comboBox.setObjectName("sequence_comboBox")
        self.comboBox_group.addWidget(self.sequence_comboBox, 1, 0, 1, 1)
        self.shot_comboBox = CompleterCombobox(self.controller)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_comboBox.sizePolicy().hasHeightForWidth())
        self.shot_comboBox.setSizePolicy(sizePolicy)
        self.shot_comboBox.setObjectName("shot_comboBox")
        self.comboBox_group.addWidget(self.shot_comboBox, 1, 1, 1, 1)
        self.header_layout.addLayout(self.comboBox_group, 0, 1, 1, 2)
        self.task_comboBox = CompleterCombobox(self.controller)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_comboBox.sizePolicy().hasHeightForWidth())
        self.task_comboBox.setSizePolicy(sizePolicy)
        self.task_comboBox.setObjectName("task_comboBox")
        self.header_layout.addWidget(self.task_comboBox, 1, 1, 1, 1)
        self.help_button = HelpButton(self.controller)
        self.help_button.setStyleSheet("border: none;")
        self.help_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bp/images/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_button.setIcon(icon)
        self.help_button.setIconSize(QtCore.QSize(20, 20))
        self.help_button.setObjectName("help_button")
        self.header_layout.addWidget(self.help_button, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.header_layout, 0, 0, 1, 1)
        self.icon_field = QtWidgets.QTabWidget(self.controller)
        self.icon_field.setTabPosition(QtWidgets.QTabWidget.North)
        self.icon_field.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.icon_field.setTabsClosable(False)
        self.icon_field.setMovable(False)
        self.icon_field.setObjectName("icon_field")
        self.artist_tab = TabListWidget()
        self.artist_tab.setObjectName("artist_tab")
        self.icon_field.addTab(self.artist_tab, "")
        self.admin_tab = TabListWidget()
        self.admin_tab.setObjectName("admin_tab")
        self.icon_field.addTab(self.admin_tab, "")
        self.test_tab = TabListWidget()
        self.test_tab.setObjectName("test_tab")
        self.icon_field.addTab(self.test_tab, "")
        self.others_tab = TabListWidget()
        self.others_tab.setObjectName("others_tab")
        self.icon_field.addTab(self.others_tab, "")
        self.gridLayout.addWidget(self.icon_field, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.controller, 0, 0, 1, 1)

        self.retranslateUi(MainWidget)
        self.icon_field.setCurrentIndex(0)
        QtCore.QObject.connect(self.show_comboBox, QtCore.SIGNAL("currentTextChanged(QString)"), self.controller.set_sequence)
        QtCore.QObject.connect(self.sequence_comboBox, QtCore.SIGNAL("currentTextChanged(QString)"), self.controller.set_shot)
        QtCore.QObject.connect(self.show_comboBox, QtCore.SIGNAL("currentTextChanged(QString)"), self.controller.set_step)
        QtCore.QObject.connect(self.entity_comboBox, QtCore.SIGNAL("currentTextChanged(QString)"), self.controller.set_step)
        QtCore.QObject.connect(self.show_comboBox, QtCore.SIGNAL("currentTextChanged(QString)"), self.controller.set_user)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        MainWidget.setWindowTitle(QtWidgets.QApplication.translate("MainWidget", "BPL", None, -1))
        self.user_label.setText(QtWidgets.QApplication.translate("MainWidget", "User:", None, -1))
        self.show_lable.setText(QtWidgets.QApplication.translate("MainWidget", "Show:", None, -1))
        self.entity_lable.setText(QtWidgets.QApplication.translate("MainWidget", "Asset:", None, -1))
        self.task_lable.setText(QtWidgets.QApplication.translate("MainWidget", "Task:", None, -1))
        self.icon_field.setTabText(self.icon_field.indexOf(self.artist_tab), QtWidgets.QApplication.translate("MainWidget", "Artist", None, -1))
        self.icon_field.setTabText(self.icon_field.indexOf(self.admin_tab), QtWidgets.QApplication.translate("MainWidget", "Admin", None, -1))
        self.icon_field.setTabText(self.icon_field.indexOf(self.test_tab), QtWidgets.QApplication.translate("MainWidget", "Test", None, -1))
        self.icon_field.setTabText(self.icon_field.indexOf(self.others_tab), QtWidgets.QApplication.translate("MainWidget", "Others", None, -1))

from bpl.view.my_control import TabListWidget, CompleterCombobox
from bpl.controller.main_controller import MainController
